-- local cmp = require("cmp")
-- local luasnip = require("luasnip")
--
-- cmp.setup({
--     snippet = {
--         expand = function(args)
--             luasnip.lsp_expand(args.body) -- Use LuaSnip for snippets
--         end,
--     },
--     mapping = cmp.mapping.preset.insert({
--         ["<C-Space>"] = cmp.mapping.complete(),
--         ["<CR>"] = cmp.mapping.confirm({ select = true }),
--         ["<Tab>"] = cmp.mapping.select_next_item(),
--         ["<S-Tab>"] = cmp.mapping.select_prev_item(),
--         -- ["<C-b>"] = cmp.mapping.scroll_docs(-4),
--         -- ["<C-f>"] = cmp.mapping.scroll_docs(4),
--         -- ["<C-Space>"] = cmp.mapping.complete(), -- manually trigger completion
--         -- ["<C-e>"] = cmp.mapping.abort(), -- close menu
--         -- ["<CR>"] = cmp.mapping.confirm({ select = true }), -- confirm selection
--     }),
--     sources = cmp.config.sources({
--         { name = "nvim_lsp" }, -- from LSP
--         -- { name = "luasnip" }, -- snippets
--         { name = "buffer" }, -- words in current buffer
--         { name = "path" }, -- file paths
--     }),
-- })
